services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1212
    volumes:
      - mongo_data:/data/db
    command: ["mongod", "--auth"]
    networks: 
      - app-network
  
  back-app:
    image: back-app
    container_name: fit_back
    restart: always
    ports: 
      - "4000:4000"
    depends_on:
      - mongo
  
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
