services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1212
    volumes:
      - mongo_data:/data/db
    command: ["mongod", "--auth"]

volumes:
  mongo_data:
